version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data
    expose:
      - 6379
    # ports:
    #   - 6379:6379    
    networks:
      - internal

  cart:
    image: maven:3.9-amazoncorretto-19
    container_name: cart
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - EUREKA_HOST=discovery-server
    networks:
      - spring_microservices
      - internal

volumes:
  maven-repo:
  redis-data:

networks:
  internal:
  spring_microservices:
    external: true