version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    

  polyshop:
    image: maven:3.9-amazoncorretto-19
    depends_on:
      - redis
    networks:
      - host
    ports:
      - 8091:8091 
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    volumes:
      - polyshop:/usr/src/app
      - .:/usr/src/app
    command: ["sh", "-c", "cd /usr/src/app; mvn spring-boot:run"]

volumes:
  polyshop:

networks:
  host:
    # This network should be connected to the host network
